### ISSUE TITLE
amclの座標系を確認

### ISSUE THREAD

**Issue by kenjirotorii** [kenjirotorii/burger_war_dev#2]
amclの座標系がどのような仕組みかを確認する

**Comment by seigot** [comment]
amclもworld座標系（gazebo_stateで返してくる座標系？）でx,y座標を返してくれるみたいに見えます。

**Comment by kenjirotorii** [comment]
amclだと、x,yの座標軸が入れ替わっているように見えます。
具体的には、x (amcl) = -y (gazebo), y (amcl) = x (gazebo)
