### ISSUE TITLE
壁回避

### ISSUE THREAD

**Issue by kenjirotorii** [kenjirotorii/burger_war_dev#3]
壁回避のアルゴリズムを考える
- [x] ルールベース：壁までの距離が一定以下になったら前進/後退
- [x] 報酬に入れる：壁までの距離が一定以下になったらマイナスの報酬

**Comment by kenkenjlab** [comment]
>  報酬に入れる：壁までの距離が一定以下になったらマイナスの報酬

c9e38cbaa54ee4760bfea81b84dc43349c5fb6a0
get_rewardの中に実装しました。
所定距離(暫定：0.3[m])以内のLiDAR点数が閾値数(暫定：90)以上存在する場合に報酬に-1を加算しています

**Comment by kenjirotorii** [comment]
壁回避再考
* 壁回避をそもそもいれない→そのあとに壁回避を入れる（２段階）
* 壁回避をルールベースでやる
* Lidarで判定（一点でも閾値以下であれば罰）
* （壁判定をLidarでなく、ジャイロ（もしくはgazeboのAPI）で判定する）
