### ISSUE TITLE
敵機のリセットが効かない

### ISSUE THREAD

**Issue by kenjirotorii** [kenjirotorii/burger_war_dev#8]
自機のリセットは上手く動作するが、敵機のリセットをしていないため、２エピソード以降は敵機が思った動きをしない。

**解決策**
* Agentを独立ノードにして、それ以外を全てリセットするようにする。Environment <-> Agentで、データとモデルの通信を行う。Agentは環境からデータを受け取り、メモリに格納し、一定間隔で学習を行う。環境側は、Agentにデータを送る、Agentからモデルのパラメータを受け取る。
* 敵機のスクリプトにもリセット機能を追加する

**Comment by kenjirotorii** [comment]
* respawnを駆使して上手くやる
* 全部キルがfirst stepでやる（データをpklに保存しておく）←これでいく

**Comment by seigot** [comment]
> 全部キルがfirst stepでやる（データをpklに保存しておく）←これでいく>

よく考えたら、敵側のamclのノードはstart.sh実行時に起動しており、敵機のリセットはstart.shをkillする事で十分ではと思ってきました。
本当に最小限に留めようとすると以下`sim_robot_run.launch`のenemy_bot起動処理のみを再起動させるのが良さそうですが、`sim_robot_run.launch`を改造する必要があり一手間掛かりそうです。

https://github.com/seigot/burger_war_kit/blob/main/burger_war/launch/sim_robot_run.launch

以下の4．のような場面で使う事を想定したreset.shを作成してみました。
https://github.com/seigot/burger_war_kit/blob/main/scripts/reset.sh

1．GAZEBO起動（bash scripts/sim_with_judge.sh）
2．学習開始（start.sh相当？）
3．学習終了
4．reset.shで敵機、自機、審判、モデル初期化


> respawnを駆使して上手くやる

こちらもよく考えたらspawn自体がモデルを生み出す処理だったはずなので、ノード初期化とは少し別かもしれませんね

**Comment by kenjirotorii** [comment]
4fe14bcc9b03b378f4c5b444917207aad664320d
